### ISSUE TITLE
Issue with test2  (io.p)

### ISSUE THREAD

**Issue by bigmanstan** [tangentcode/learntris#54]
why is test2 failing with the following code in "learntris.py"

[http://pastebin.com/MH7HYYEC](http://pastebin.com/MH7HYYEC)

it produces the said pattern correctly :/

and im using the `./testris.py --shell ./learntris.py` command to run it in linux terminal.

**Comment by amustafa15** [comment]
You were right. Your code does produce the right output but the computer doesn't know which interpreter to execute the script. Try adding 

#!/usr/bin/python

to the top of your script. I passed test 2 after inserting that shebang in place of your #learntris v.01 or whatever you put at the top. The #!/usr/bin/python shebang is used to tell the computer which interpreter you want to execute a script.

**Comment by amustafa15** [comment]
#!/usr/bin/python
def test2():
    while True:
        qp = raw_input('')
        if qp == 'p':

            for i in range(0, 22):
                for j in range(0, 10):
                    print'.',
                print''
        else:
            return exit()


test2()

here's what it looks like

**Comment by amustafa15** [comment]
```
#!/usr/bin/python
def test2():
    while True:
        qp = raw_input('')
        if qp == 'p':

            for i in range(0, 22):
                for j in range(0, 10):
                    print'.',
                print''
        else:
            return exit()


test2()

```
